### PR TITLE
unsupported webgpu logic so it fails gracefully

### LINKED ISSUE #1414: Website https://www.cogentcore.org/core/ doesn't work on Windows for ARM64 (stuck at 99%)
### Discussed in https://github.com/cogentcore/core/discussions/1413

<div type='discussions-op-text'>

<sup>Originally posted by **SideFx** January  2, 2025</sup>
Used Chrome & Edge as browser. Progress bar stucks at 99%.
Any ideas?
Thank you.
</div>

### PR DESCRIPTION
**Pull request by rcoreilly**
*From @kkoreilly: Fixes #1414*

### CODE REVIEW

File: gpu/gpu.go [hunk 1]
```diff
@@ -38,6 +39,10 @@ var (
 	// are listed in order 0..n-1.
 	SelectAdapter = -1
 
+	// Unsupported is set to true if the first attempt to get a valid GPU
+	// device fails.
+	Unsupported = false
```
Comment (kkoreilly) [inline gpu/gpu.go]: Do we really need this?

**Review by kkoreilly — CHANGES_REQUESTED** [review]

File: gpu/gpu.go (hunk 1 above)
Comment (rcoreilly) [reply gpu/gpu.go]: I thought we did for your web logic, but I guess not. I will remove.

**Review by kkoreilly — APPROVED** [review]
