### PR TITLE
renderwindow resized is now much more parsimonious if everything is the same

### LINKED ISSUE #1438: Moving a window ends up calling resized() with same size: need to do less when that happens
### Describe the bug

see renderwindow.go: 284 case where curRg == rg -- this causes any open dialogs with textfield to lose their edits, for example.

is only rarely actually necessary to do something here: figure out the right conditions and only do it then!

also cogent code is doing too much here: tree seems to be redoing git repo file loading which is slow, for example -- trace it.

### How to reproduce

move windows

### Example code

```go

```

### Relevant output

```shell

```

### Platform

macOS

### PR DESCRIPTION
**Pull request by rcoreilly**
Fixes #1438

### CODE REVIEW

File: core/renderwindow.go [hunk 1]
```diff
@@ -284,17 +284,22 @@ func (w *renderWindow) resized() {
...
-		// still need to apply style even if size is same
-		for _, kv := range w.mains.stack.Order {
-			st := kv.Value
-			sc := st.Scene
-			if st.FullWindow && sc.SceneGeom.Size != rg.Size { // double-check: can be off in fullscreen init
-				st.Sprites.reset()
-				sc.resize(rg)
+		newDPI := false
+		if rc.logicalDPI != w.logicalDPI() {
+			rc.logicalDPI = w.logicalDPI()
```
Comment (kkoreilly) [inline core/renderwindow.go]: Is `w.logicalDPI()` sufficiently nontrivial to justify a local variable here?

File: core/renderwindow.go [hunk 2]
```diff
@@ -284,17 +284,22 @@ func (w *renderWindow) resized() {
...
+		}
+		if w.mains.resize(rg) || newDPI {
+			// still need to apply style even if size is same
+			for _, kv := range w.mains.stack.Order {
+				st := kv.Value
+				sc := st.Scene
+				// if st.FullWindow && sc.SceneGeom.Size != rg.Size { // double-check: can be off in fullscreen init
+				// 	st.Sprites.reset()
+				// 	sc.resize(rg)
+				// }
```
Comment (kkoreilly) [inline core/renderwindow.go]: What is happening here?

**Comment by rcoreilly** [comment]
This eliminates the long lags in cogent code from resizing -- there were multiple resized events being generated at the same size and it was redoing everything multiple times. also same with general resize resource blips.

**Review by kkoreilly — CHANGES_REQUESTED** [review]

File: core/renderwindow.go (hunk 2 above)
Comment (rcoreilly) [reply core/renderwindow.go]: right thanks -- need to nuke that now that it is working.

Comment (rcoreilly) [reply core/renderwindow.go]: was there something different about fullscreen on windows vs. mac though? do I need to test it there?

Comment (kkoreilly) [reply core/renderwindow.go]: It does seem to work for me on mac with the initial fullscreen state. I don't think there is anything different on Windows. Can you explain why this PR removes the need for that code? It was definitely needed before.

Comment (rcoreilly) [reply core/renderwindow.go]: ok tested there just for good measure -- looks good.

File: core/renderwindow.go (hunk 1 above)
Comment (rcoreilly) [reply core/renderwindow.go]: ?

**Review by kkoreilly — APPROVED** [review]
