### PR TITLE
Fix for #1387 -- layout logic says that bounding box should be based on Alloc, not Actual; also fix form stale closure issue using field path

### LINKED ISSUE #1387: form layout is too small from at least multiple spinner elements in add-fields. Present already in 0.3.0 initial release.
### Describe the bug

axon.LayerParams and PathParms exhibit the problem. 

when I comment-out the shouldDisplay logic, the problem goes away.

Also, shouldDisplay inline fields are causing crashing due to stale captured values in the maker updater.

### How to reproduce

run current axon, edit LayerParams or PathParams

working on making a reproducible test case

### Example code

_No response_

### Relevant output

_No response_

### Platform

macOS

### LINKED ISSUE #1390: form shouldDisplay logic causes crash due to stale captured variables -- updated demo to reveal
### Describe the bug

form contains code like this inside field closures:

```Go
					w.Styler(func(s *styles.Style) {
						f := fm.structFields[i]
```

but the value of `i` depends on what was actually  shown previously, so it can crash with out-of-range errors here. this happens in axon, and I updated the order of fields in demo to show it.

we need a canonical path name, not an index, and to find the field data by that path name.

### How to reproduce

open demo, click things in the first inline guy.

### Example code

_No response_

### Relevant output

_No response_

### Platform

macOS

### PR DESCRIPTION
**Pull request by rcoreilly**
Fixes #1387, fixes #1390

### CODE REVIEW

File: core/layout.go [hunk 1]
```diff
@@ -295,13 +295,13 @@ func (ls *geomState) contentRangeDim(d math32.Dims) (cmin, cmax float32) {
 // totalRect returns Pos.Total -- Size.Actual.Total
 // as an image.Rectangle, e.g., for bounding box
 func (ls *geomState) totalRect() image.Rectangle {
-	return math32.RectFromPosSizeMax(ls.Pos.Total, ls.Size.Actual.Total)
```
Comment (kkoreilly) [inline core/layout.go:297]: We had the previous behavior for a reason; I think it might have been related to border, shadow, scrollbar, or parent border radius rendering or something. See https://github.com/cogentcore/core/commit/c3ca7fa41d79826f21612532fa7524432e35bee8; you must test very thoroughly.

Comment (rcoreilly) [reply core/layout.go:297]: The only tests that differ in my local run were 2 scrollbar things that seem like they were incorrect before.

Comment (kkoreilly) [reply core/layout.go:297]: This was the commit I was thinking of where we previously switched to using actual in another context to fix #1012: 316494b28b932079d29ccaba87406a1a2ef54323

Comment (rcoreilly) [reply core/layout.go:297]: I just pushed a key fix to remove the spacing change in my form test. You can verify that the test we wrote for that issue is _not_ affected by this change. Furthermore if you look at the layout logic, it is essential that the bounding box be given by the alloc, because that is what is used for arranging items within a frame. Most of the time we weren't noticing this issue because most frames that do significant layout are also grow, which eliminates this differnece between actual and alloc, so this was showing up in form because we turned grow off.

**Comment by rcoreilly** [comment]
ps will rename Actual -> Need in a later PR to make it clearer what it "actually" is.

**Comment by rcoreilly** [comment]
ok now actually fully ready  :)

File: core/form.go [hunk 2]
```diff
@@ -109,10 +110,11 @@ func (fm *Form) getStructFields() {
 						if field.Tag.Get("edit") == "-" && sfield.Tag.Get("edit") == "" {
 							sfield.Tag += ` edit:"-"`
 						}
-						fields = append(fields, &structField{path: field.Name + " • " + sfield.Name, field: sfield, value: value, parent: parent})
+						path := field.Name + " • " + sfield.Name
+						fields.Add(path, &structField{path: path, field: sfield, value: value, parent: parent})
```
Comment (kkoreilly) [inline core/form.go:114]: We are using the user-friendly bullet text for the map key?

File: core/form.go [hunk 3]
```diff
@@ -167,7 +171,7 @@ func (fm *Form) Init() {
 			// as the ground truth everywhere. The index could otherwise become invalid,
 			// such as when a ShouldDisplayer condition is newly satisfied
 			// (see https://github.com/cogentcore/core/issues/1096).
```
Comment (kkoreilly) [inline core/form.go]: This documentation is out-of-date.

File: core/form.go [hunk 4]
```diff
@@ -190,7 +194,7 @@ func (fm *Form) Init() {
 					}
```
Comment (kkoreilly) [inline core/form.go:193]: You are still not recomputing doc, readOnlyTag, def, hasDef, etc every time. This does **not** address #1098; that really is for rare cases, which are different from those this PR addresses.

**Review by kkoreilly — CHANGES_REQUESTED** [review]

**Review by kkoreilly — APPROVED** [review]
