### PR TITLE
switch to WebGPU instead of Vulkan for 3D / 2D rendering.

### LINKED ISSUE #290: Windows 10 - Installation issues
I've just follow up the docs to install this library but when I just want to try a basic examples it's says that some packages were not found. 

So It would be helpfull to understand how does this works to improove the installation docs.
I think it can be better.

Could you please at least update the installation on windows to get this working?

### LINKED ISSUE #481: Problem with vgpu when installing GoGi and building widgets
Just tried to install gogi and build widgets.  Latest version of macOS BigSur and go1.19.  Got the following error.

[github.com/goki/gi/gimain](http://github.com/goki/gi/gimain)
[github.com/goki/gi/examples/widgets](http://github.com/goki/gi/examples/widgets)
reads-Mac-mini:widgets read$ ./widgets
panic: vulkan error: vulkan error: incompatible driver (-9) on /Users/read/go/pkg/mod/[github.com/goki/vgpu@v1.0.5/vgpu/errors.go:23](http://github.com/goki/vgpu@v1.0.5/vgpu/errors.go:23) (0x459d1be)
	NewError: pc, _, _, ok := runtime.Caller(0)

goroutine 1 [running, locked to thread]:
[github.com/goki/vgpu/vgpu.IfPanic](http://github.com/goki/vgpu/vgpu.IfPanic)(...)
	/Users/read/go/pkg/mod/[github.com/goki/vgpu@v1.0.5/vgpu/errors.go:40](http://github.com/goki/vgpu@v1.0.5/vgpu/errors.go:40)
[github.com/goki/vgpu/vgpu](http://github.com/goki/vgpu/vgpu).(*GPU).Config(0xc00043b000, {0x4e12151?, 0x4e42ef3?})
	/Users/read/go/pkg/mod/[github.com/goki/vgpu@v1.0.5/vgpu/gpu.go:172](http://github.com/goki/vgpu@v1.0.5/vgpu/gpu.go:172) +0xbb5
[github.com/goki/gi/oswin/driver/vkos](http://github.com/goki/gi/oswin/driver/vkos).(*appImpl).initVk(0x5f0db80)
	/Users/read/go/gi/oswin/driver/vkos/app.go:195 +0x22a
[github.com/goki/gi/oswin/driver/vkos.Main](http://github.com/goki/gi/oswin/driver/vkos.Main)(0x4bba0a0?)
	/Users/read/go/gi/oswin/driver/vkos/app.go:74 +0x45
[github.com/goki/gi/oswin/driver.driverMain](http://github.com/goki/gi/oswin/driver.driverMain)(...)
	/Users/read/go/gi/oswin/driver/driver_vkos.go:18
[github.com/goki/gi/oswin/driver.Main](http://github.com/goki/gi/oswin/driver.Main)(...)
	/Users/read/go/gi/oswin/driver/driver.go:27
[github.com/goki/gi/gimain.Main](http://github.com/goki/gi/gimain.Main)(0x4efe160?)
	/Users/read/go/gi/gimain/gimain.go:31 +0x57
main.main()
	/Users/read/go/gi/examples/widgets/widgets.go:24 +0x25
reads-Mac-mini:widgets read$

### LINKED ISSUE #483: Failure on fresh Debian 11
I created a new Debian 11 64-bit VM inside VirtualBox and installed Go 1.19 by unpacking the binary. I used apt to install the dependencies listed in the Install doc. Then I tried to install and build, but it failed:
```
mark@debianvm:~/opt$ git clone https://github.com/goki/gi
Cloning into 'gi'...
remote: Enumerating objects: 20652, done.
... elided ...
Resolving deltas: 100% (15942/15942), done.
mark@debianvm:~/opt$ cd gi/examples/widgets/
mark@debianvm:~/opt/gi/examples/widgets$ go build -v
go: downloading github.com/goki/ki v1.1.8
... elided ...
github.com/go-gl/glfw/v3.3/glfw
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../../gows/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220516021902-eb3e265c7661/c_glfw_lin.go:20:
../../../gows/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220516021902-eb3e265c7661/glfw/src/x11_window.c:30: warning: "_GNU_SOURCE" redefined
   30 | #define _GNU_SOURCE
      | 
<command-line>: note: this is the location of the previous definition
github.com/goki/gi/oswin/driver/internal/event
github.com/goki/gi/oswin/driver/vkos
github.com/goki/gi/gi3d
github.com/goki/gi/gi3d/io/obj
github.com/goki/gi/oswin/driver
github.com/goki/gi/svg
github.com/goki/gi/gimain
github.com/goki/gi/examples/widgets
mark@debianvm:~/opt/gi/examples/widgets$ ./widgets
2022/12/02 08:43:20 vulkan warning: missing 1 required device extensions during Config
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f9e3cecdf70]

runtime stack:
runtime.throw({0x12af97a?, 0x7f9e3fce5211?})
	/home/mark/opt/go/src/runtime/panic.go:1047 +0x5d fp=0x7ffc5e00f038 sp=0x7ffc5e00f008 pc=0x44aedd
runtime.sigpanic()
	/home/mark/opt/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7ffc5e00f088 sp=0x7ffc5e00f038 pc=0x4614a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xfdcdf0, 0xc000021ca8)
	/home/mark/opt/go/src/runtime/cgocall.go:158 +0x5c fp=0xc000021c80 sp=0xc000021c48 pc=0x417c5c
github.com/goki/vulkan._Cfunc_callVkCreateCommandPool(0x0, 0x27b6d60, 0x0, 0xc000545dd8)
	_cgo_gotypes.go:7932 +0x4c fp=0xc000021ca8 sp=0xc000021c80 pc=0x96ec2c
github.com/goki/vulkan.CreateCommandPool.func1(0x0, 0x0?, 0xc000021d30?, 0x4219e7?)
	/home/mark/opt/gows/pkg/mod/github.com/goki/vulkan@v0.0.0-20220928215615-c67065a9cfc2/vulkan.go:841 +0xb1 fp=0xc000021cf8 sp=0xc000021ca8 pc=0x9a1e31
github.com/goki/vulkan.CreateCommandPool(0x0, 0x9a4f8f?, 0x7f9e3d91ce60?, 0x8?)
	/home/mark/opt/gows/pkg/mod/github.com/goki/vulkan@v0.0.0-20220928215615-c67065a9cfc2/vulkan.go:841 +0x47 fp=0xc000021d40 sp=0xc000021cf8 pc=0x9a1d27
github.com/goki/vgpu/vgpu.(*CmdPool).ConfigResettable(0xc0003ed538, 0xc0003ed520)
	/home/mark/opt/gows/pkg/mod/github.com/goki/vgpu@v1.0.5/vgpu/cmds.go:36 +0x7f fp=0xc000021dc0 sp=0xc000021d40 pc=0x9c1f1f
github.com/goki/vgpu/vgpu.(*System).InitCmd(0x9d15a9?)
	/home/mark/opt/gows/pkg/mod/github.com/goki/vgpu@v1.0.5/vgpu/system.go:60 +0x30 fp=0xc000021df0 sp=0xc000021dc0 pc=0x9d30b0
github.com/goki/vgpu/vgpu.(*System).InitGraphics(0xc0003ed508, 0xc0003dd800, {0x1265fa3?, 0x27b3a10?}, 0xc0003a6dc0?)
	/home/mark/opt/gows/pkg/mod/github.com/goki/vgpu@v1.0.5/vgpu/system.go:41 +0x85 fp=0xc000021e18 sp=0xc000021df0 pc=0x9d2f05
github.com/goki/vgpu/vdraw.(*Drawer).ConfigSurface(0xc0003ed508, 0xc0003a6dc0, 0xc000545d88?)
	/home/mark/opt/gows/pkg/mod/github.com/goki/vgpu@v1.0.5/vdraw/vdraw.go:35 +0x65 fp=0xc000021e58 sp=0xc000021e18 pc=0x9e32c5
github.com/goki/gi/oswin/driver/vkos.(*appImpl).NewWindow.func2()
	/home/mark/opt/gi/oswin/driver/vkos/app.go:248 +0xf2 fp=0xc000021eb0 sp=0xc000021e58 pc=0xf29992
github.com/goki/gi/oswin/driver/vkos.(*appImpl).mainLoop(0x1ebf740)
	/home/mark/opt/gi/oswin/driver/vkos/app.go:158 +0x104 fp=0xc000021f30 sp=0xc000021eb0 pc=0xf28724
github.com/goki/gi/oswin/driver/vkos.Main(0xfdbca0?)
	/home/mark/opt/gi/oswin/driver/vkos/app.go:80 +0x91 fp=0xc000021f48 sp=0xc000021f30 pc=0xf28231
github.com/goki/gi/oswin/driver.driverMain(...)
	/home/mark/opt/gi/oswin/driver/driver_vkos.go:18
github.com/goki/gi/oswin/driver.Main(...)
	/home/mark/opt/gi/oswin/driver/driver.go:27
github.com/goki/gi/gimain.Main(0x131b120?)
	/home/mark/opt/gi/gimain/gimain.go:31 +0x57 fp=0xc000021f68 sp=0xc000021f48 pc=0xfd58d7
main.main()
	/home/mark/opt/gi/examples/widgets/widgets.go:24 +0x25 fp=0xc000021f80 sp=0xc000021f68 pc=0xfd5ac5
runtime.main()
	/home/mark/opt/go/src/runtime/proc.go:250 +0x212 fp=0xc000021fe0 sp=0xc000021f80 pc=0x44d732
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000021fe8 sp=0xc000021fe0 pc=0x47c081

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/mark/opt/go/src/runtime/proc.go:363 +0xd6 fp=0xc00005efb0 sp=0xc00005ef90 pc=0x44daf6
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/home/mark/opt/go/src/runtime/proc.go:302 +0xad fp=0xc00005efe0 sp=0xc00005efb0 pc=0x44d98d
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x47c081
created by runtime.init.6
	/home/mark/opt/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/mark/opt/go/src/runtime/proc.go:363 +0xd6 fp=0xc00005f790 sp=0xc00005f770 pc=0x44daf6
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/home/mark/opt/go/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc00005f7c8 sp=0xc00005f790 pc=0x4390d7
runtime.gcenable.func1()
	/home/mark/opt/go/src/runtime/mgc.go:178 +0x26 fp=0xc00005f7e0 sp=0xc00005f7c8 pc=0x42dd46
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x47c081
created by runtime.gcenable
	/home/mark/opt/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [runnable]:
runtime.gopark(0xc00008c000?, 0xdbab26de84?, 0x0?, 0x0?, 0x131b4c0?)
	/home/mark/opt/go/src/runtime/proc.go:363 +0xd6 fp=0xc00005ff30 sp=0xc00005ff10 pc=0x44daf6
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:369
runtime.(*scavengerState).sleep(0x237cb20, 0x410655d000000000)
	/home/mark/opt/go/src/runtime/mgcscavenge.go:468 +0x125 fp=0xc00005ffa0 sp=0xc00005ff30 pc=0x437345
runtime.bgscavenge(0x0?)
	/home/mark/opt/go/src/runtime/mgcscavenge.go:626 +0x7f fp=0xc00005ffc8 sp=0xc00005ffa0 pc=0x43773f
runtime.gcenable.func2()
	/home/mark/opt/go/src/runtime/mgc.go:179 +0x26 fp=0xc00005ffe0 sp=0xc00005ffc8 pc=0x42dce6
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x47c081
created by runtime.gcenable
	/home/mark/opt/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0xc0002094b0?, 0x30?, 0x54?, 0x1000000010?)
	/home/mark/opt/go/src/runtime/proc.go:363 +0xd6 fp=0xc00005e628 sp=0xc00005e608 pc=0x44daf6
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:369
runtime.runfinq()
	/home/mark/opt/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00005e7e0 sp=0xc00005e628 pc=0x42ce4f
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x47c081
created by runtime.createfing
	/home/mark/opt/go/src/runtime/mfinal.go:157 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0xdb6f883d66?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/mark/opt/go/src/runtime/proc.go:363 +0xd6 fp=0xc000060750 sp=0xc000060730 pc=0x44daf6
runtime.gcBgMarkWorker()
	/home/mark/opt/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000607e0 sp=0xc000060750 pc=0x42fe91
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x47c081
created by runtime.gcBgMarkStartWorkers
	/home/mark/opt/go/src/runtime/mgc.go:1159 +0x25

goroutine 7 [runnable]:
runtime.gopark(0xf1e565?, 0xc00004c000?, 0x5c?, 0x7c?, 0xc0006579d8?)
	/home/mark/opt/go/src/runtime/proc.go:363 +0xd6 fp=0xc0006579a8 sp=0xc000657988 pc=0x44daf6
runtime.chansend(0xc00003c6c0, 0xc000657a78, 0x1, 0xc000555488?)
	/home/mark/opt/go/src/runtime/chan.go:259 +0x42c fp=0xc000657a30 sp=0xc0006579a8 pc=0x419e4c
runtime.chansend1(0xc000657a88?, 0x0?)
	/home/mark/opt/go/src/runtime/chan.go:145 +0x1d fp=0xc000657a60 sp=0xc000657a30 pc=0x4199fd
github.com/goki/gi/oswin/driver/vkos.(*appImpl).RunOnMain(0x1ebf740, 0xc000555488)
	/home/mark/opt/gi/oswin/driver/vkos/app.go:95 +0x6c fp=0xc000657a98 sp=0xc000657a60 pc=0xf282cc
github.com/goki/gi/oswin/driver/vkos.(*appImpl).NewWindow(0x1ebf740, 0xc0004a0540?)
	/home/mark/opt/gi/oswin/driver/vkos/app.go:241 +0x3a8 fp=0xc000657b38 sp=0xc000657a98 pc=0xf29148
github.com/goki/gi/gi.NewWindow({0x127cb24, 0x11}, {0x127a68d, 0x11}, 0xc00006fbe8?)
	/home/mark/opt/gi/gi/window.go:345 +0x157 fp=0xc000657ba0 sp=0xc000657b38 pc=0xc2ccf7
github.com/goki/gi/gi.NewMainWindow({0x127cb24, 0x11}, {0x127a68d, 0x11}, 0x400, 0x300)
	/home/mark/opt/gi/gi/window.go:393 +0x145 fp=0xc000657bf8 sp=0xc000657ba0 pc=0xc2d165
main.mainrun()
	/home/mark/opt/gi/examples/widgets/widgets.go:49 +0xf4 fp=0xc000657fa0 sp=0xc000657bf8 pc=0xfd6cb4
main.main.func1()
	/home/mark/opt/gi/examples/widgets/widgets.go:25 +0x17 fp=0xc000657fb0 sp=0xc000657fa0 pc=0xfd5a77
github.com/goki/gi/gimain.Main.func1({0x0?, 0x0?})
	/home/mark/opt/gi/gimain/gimain.go:32 +0x1b fp=0xc000657fc0 sp=0xc000657fb0 pc=0xfd591b
github.com/goki/gi/oswin/driver/vkos.Main.func1()
	/home/mark/opt/gi/oswin/driver/vkos/app.go:77 +0x2e fp=0xc000657fe0 sp=0xc000657fc0 pc=0xf2816e
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000657fe8 sp=0xc000657fe0 pc=0x47c081
created by github.com/goki/gi/oswin/driver/vkos.Main
	/home/mark/opt/gi/oswin/driver/vkos
```

### LINKED ISSUE #507: Add WebGPU support
Likely through a wrapper on WebGPU using vGPU and GopherJS.

### LINKED ISSUE #682: Implement a vulkan-free driver for VMs and old devices
It would be useful to be able to run in virtual machines and remote desktops.

Vulkan in software may be getting better in various forms (mesa, some other thing that android or ios uses in its simulator).

Alternatively, the 2D framework is now working well using non-vulkan impl of drawer interface -- could reasonably support 2D only using a much simpler API that only uses this bitmap-based interface, running on some kind of really basic glfw window interface (not even opengl).  That would be worth it for allowing majority of apps to run in VMs etc.

See #483 for example where it doesn't work.

### LINKED ISSUE #911: manjaro linux build error
### Describe the bug

see png

### How to reproduce

run core demo

### Example code

_No response_

### Relevant output

_No response_

### Platform

Linux

### LINKED ISSUE #1017: Occasional cgo crashing on app startup on macOS
### Describe the bug

When starting an app on macOS, it occasionally crashes during cgo execution. This seems to have started happening relatively recently.

### How to reproduce

Run the docs many times on macOS until they crash.

### Example code

_No response_

### Relevant output

```shell
SIGSEGV: segmentation violation
PC=0x1080b28a4 m=0 sigcode=2 addr=0x0
signal arrived during cgo execution

goroutine 1 gp=0x140000021c0 m=0 mp=0x106d09e20 [syscall, locked to thread]:
runtime.cgocall(0x1056fc848, 0x1400004d1a8)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/cgocall.go:157 +0x44 fp=0x1400004d160 sp=0x1400004d120 pc=0x1048c3274
github.com/goki/vulkan._Cfunc_callVkCreateGraphicsPipelines(0x15906a218, 0x15672e660, 0x1, 0x15672e700, 0x0, 0x14013378b10)
        _cgo_gotypes.go:8402 +0x34 fp=0x1400004d1a0 sp=0x1400004d160 pc=0x104bd9a94
github.com/goki/vulkan.CreateGraphicsPipelines.func1(0x15906a218, 0x15672e660, 0x1, 0x15672e700, 0x0, 0x14013378b10)
        /Users/kaioreilly/go/pkg/mod/github.com/goki/vulkan@v1.0.7/vulkan.go:643 +0xe8 fp=0x1400004d200 sp=0x1400004d1a0 pc=0x104c05d98
github.com/goki/vulkan.CreateGraphicsPipelines(0x15906a218, 0x15672e660, 0x1, {0x1400004d478, 0x1, 0x0?}, 0x0, {0x14013378b10, 0x1, 0x1})
        /Users/kaioreilly/go/pkg/mod/github.com/goki/vulkan@v1.0.7/vulkan.go:643 +0x84 fp=0x1400004d340 sp=0x1400004d200 pc=0x104c05ae4
cogentcore.org/core/vgpu.(*Pipeline).Config(0x14011070800, 0x88?)
        /Users/kaioreilly/cogent/core/vgpu/pipeline.go:197 +0x470 fp=0x1400004d540 sp=0x1400004d340 pc=0x104c38580
cogentcore.org/core/vgpu.(*System).Config(0x14012cfb208)
        /Users/kaioreilly/cogent/core/vgpu/system.go:283 +0x100 fp=0x1400004d5c0 sp=0x1400004d540 pc=0x104c3ea80
cogentcore.org/core/vgpu/vdraw.(*Drawer).ConfigSys(0x14012cfb208)
        /Users/kaioreilly/cogent/core/vgpu/vdraw/config.go:106 +0x7bc fp=0x1400004d750 sp=0x1400004d5c0 pc=0x104c4db1c
cogentcore.org/core/vgpu/vdraw.(*Drawer).ConfigSurface(0x14012cfb208, 0x14012cb2b00, 0x0?)
        /Users/kaioreilly/cogent/core/vgpu/vdraw/vdraw.go:53 +0x9c fp=0x1400004d790 sp=0x1400004d750 pc=0x104c501cc
cogentcore.org/core/system/driver/desktop.(*App).NewWindow.func2()
        /Users/kaioreilly/cogent/core/system/driver/desktop/app.go:139 +0xbc fp=0x1400004d7e0 sp=0x1400004d790 pc=0x104d89e0c
cogentcore.org/core/system/driver/base.(*App).RunOnMain(0x140003c86c0?, 0x106d07200?)
        /Users/kaioreilly/cogent/core/system/driver/base/app.go:90 +0xac fp=0x1400004d820 sp=0x1400004d7e0 pc=0x104bd71dc
cogentcore.org/core/system/driver/desktop.(*App).NewWindow(0x106d07200, 0x140003c86c0?)
        /Users/kaioreilly/cogent/core/system/driver/desktop/app.go:135 +0x3cc fp=0x1400004db70 sp=0x1400004d820 pc=0x104d8964c
cogentcore.org/core/core.newRenderWindow({0x140000bf530, 0x22}, {0x105727282, 0x10}, 0x140003c86c0)
        /Users/kaioreilly/cogent/core/core/renderwindow.go:108 +0xa0 fp=0x1400004dbd0 sp=0x1400004db70 pc=0x104f54c80
cogentcore.org/core/core.(*Stage).newRenderWindow(0x14000240960)
        /Users/kaioreilly/cogent/core/core/mainstage.go:348 +0x1e0 fp=0x1400004dc70 sp=0x1400004dbd0 pc=0x104f4e1b0
cogentcore.org/core/core.(*Stage).runWindow(0x14000240960)
        /Users/kaioreilly/cogent/core/core/mainstage.go:226 +0x620 fp=0x1400004dd30 sp=0x1400004dc70 pc=0x104f4d8c0
cogentcore.org/core/core.(*Stage).run(0x14000240960?)
        /Users/kaioreilly/cogent/core/core/stage.go:280 +0x8c fp=0x1400004dd60 sp=0x1400004dd30 pc=0x104f6784c
cogentcore.org/core/core.(*Stage).Run(0x14000000000?)
        /Users/kaioreilly/cogent/core/core/stage.go:259 +0x8c fp=0x1400004dd90 sp=0x1400004dd60 pc=0x104f6770c
cogentcore.org/core/core.(*Body).RunWindow(0x1?)
        /Users/kaioreilly/cogent/core/core/mainstage.go:69 +0x34 fp=0x1400004ddb0 sp=0x1400004dd90 pc=0x104f4c914
cogentcore.org/core/core.(*Body).RunMainWindow(0x105fc2520?)
        /Users/kaioreilly/cogent/core/core/mainstage.go:59 +0x134 fp=0x1400004de10 sp=0x1400004ddb0 pc=0x104f4c7b4
main.main()
        /Users/kaioreilly/cogent/core/docs/docs.go:123 +0x73c fp=0x1400004df40 sp=0x1400004de10 pc=0x1056db2ac
runtime.main()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:271 +0x28c fp=0x1400004dfd0 sp=0x1400004df40 pc=0x1048fa57c
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400004dfd0 sp=0x1400004dfd0 pc=0x104930bc4

goroutine 2 gp=0x14000002c40 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000074f90 sp=0x14000074f70 pc=0x1048fa9a8
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:408
runtime.forcegchelper()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:326 +0xb8 fp=0x14000074fd0 sp=0x14000074f90 pc=0x1048fa838
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000074fd0 sp=0x14000074fd0 pc=0x104930bc4
created by runtime.init.6 in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:314 +0x24

goroutine 18 gp=0x14000104380 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000070760 sp=0x14000070740 pc=0x1048fa9a8
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:408
runtime.bgsweep(0x14000110000)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgcsweep.go:318 +0x108 fp=0x140000707b0 sp=0x14000070760 pc=0x1048e5638
runtime.gcenable.gowrap1()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:203 +0x28 fp=0x140000707d0 sp=0x140000707b0 pc=0x1048d97d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140000707d0 sp=0x140000707d0 pc=0x104930bc4
created by runtime.gcenable in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:203 +0x6c

goroutine 19 gp=0x14000104540 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x105e926e8?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000070f60 sp=0x14000070f40 pc=0x1048fa9a8
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x106d06fc0)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgcscavenge.go:425 +0x5c fp=0x14000070f90 sp=0x14000070f60 pc=0x1048e2fbc
runtime.bgscavenge(0x14000110000)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgcscavenge.go:658 +0xac fp=0x14000070fb0 sp=0x14000070f90 pc=0x1048e357c
runtime.gcenable.gowrap2()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:204 +0x28 fp=0x14000070fd0 sp=0x14000070fb0 pc=0x1048d9778
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000070fd0 sp=0x14000070fd0 pc=0x104930bc4
created by runtime.gcenable in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:204 +0xac

goroutine 20 gp=0x14000104a80 m=nil [finalizer wait]:
runtime.gopark(0x0?, 0x1401307f3a0?, 0x20?, 0x40?, 0x1000000010?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000088d80 sp=0x14000088d60 pc=0x1048fa9a8
runtime.runfinq()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mfinal.go:194 +0x108 fp=0x14000088fd0 sp=0x14000088d80 pc=0x1048d88a8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000088fd0 sp=0x14000088fd0 pc=0x104930bc4
created by runtime.createfing in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mfinal.go:164 +0x80

goroutine 21 gp=0x14000104e00 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000071730 sp=0x14000071710 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x140000717d0 sp=0x14000071730 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140000717d0 sp=0x140000717d0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 34 gp=0x1400048e000 m=nil [GC worker (idle)]:
runtime.gopark(0x106d75660?, 0x1?, 0xdf?, 0xbe?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000494730 sp=0x14000494710 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x140004947d0 sp=0x14000494730 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140004947d0 sp=0x140004947d0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 3 gp=0x14000003500 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99eec4ce?, 0x3?, 0xac?, 0xe8?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000075730 sp=0x14000075710 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x140000757d0 sp=0x14000075730 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140000757d0 sp=0x140000757d0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 35 gp=0x1400048e1c0 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99df9764?, 0x3?, 0xea?, 0x5d?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000494f30 sp=0x14000494f10 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x14000494fd0 sp=0x14000494f30 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000494fd0 sp=0x14000494fd0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 4 gp=0x140000036c0 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99eebd7b?, 0x1?, 0x7c?, 0xda?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000075f30 sp=0x14000075f10 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x14000075fd0 sp=0x14000075f30 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000075fd0 sp=0x14000075fd0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 36 gp=0x1400048e380 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99f04a4b?, 0x1?, 0x6a?, 0xc9?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000495730 sp=0x14000495710 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x140004957d0 sp=0x14000495730 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140004957d0 sp=0x140004957d0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 5 gp=0x14000003880 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99eec47b?, 0x1?, 0x93?, 0x2e?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000076730 sp=0x14000076710 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x140000767d0 sp=0x14000076730 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140000767d0 sp=0x140000767d0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 37 gp=0x1400048e540 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99f04a21?, 0x3?, 0x83?, 0x29?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000495f30 sp=0x14000495f10 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x14000495fd0 sp=0x14000495f30 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000495fd0 sp=0x14000495fd0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 38 gp=0x1400048e700 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99ef3328?, 0x3?, 0x37?, 0x99?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000496730 sp=0x14000496710 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x140004967d0 sp=0x14000496730 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x140004967d0 sp=0x140004967d0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 6 gp=0x14000003a40 m=nil [GC worker (idle)]:
runtime.gopark(0x3b4f99f044ec?, 0x3?, 0x38?, 0x5b?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000076f30 sp=0x14000076f10 pc=0x1048fa9a8
runtime.gcBgMarkWorker()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1310 +0xd8 fp=0x14000076fd0 sp=0x14000076f30 pc=0x1048db8d8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000076fd0 sp=0x14000076fd0 pc=0x104930bc4
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/mgc.go:1234 +0x28

goroutine 12 gp=0x14000584fc0 m=nil [runnable]:
runtime.mapaccess1_faststr(0x105fca900, 0x14003212000, {0x14000294d20, 0x8})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/map_faststr.go:13 +0x3d4 fp=0x1400008fec0 sp=0x1400008fec0 pc=0x1048d2354
cogentcore.org/core/spell.(*Model).createSuggestKeys(0x14000260280, {0x14003350a99, 0x9})
        /Users/kaioreilly/cogent/core/spell/model.go:115 +0x78 fp=0x1400008ff60 sp=0x1400008fec0 pc=0x105147b98
cogentcore.org/core/spell.(*Model).addSuggestionsForWords(0x14000260280, {0x14003542000, 0x7fc0, 0x0?})
        /Users/kaioreilly/cogent/core/spell/model.go:68 +0x60 fp=0x1400008ffa0 sp=0x1400008ff60 pc=0x105147650
cogentcore.org/core/spell.(*Model).SetDicts.gowrap1()
        /Users/kaioreilly/cogent/core/spell/model.go:60 +0x34 fp=0x1400008ffd0 sp=0x1400008ffa0 pc=0x1051475b4
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400008ffd0 sp=0x1400008ffd0 pc=0x104930bc4
created by cogentcore.org/core/spell.(*Model).SetDicts in goroutine 1
        /Users/kaioreilly/cogent/core/spell/model.go:60 +0x13c

r0      0x1
r1      0x107257200
r2      0x15672ee60
r3      0x2a
r4      0x52204000
r5      0x2a
r6      0x0
r7      0x19796bd7
r8      0x1
r9      0x15987e628
r10     0x179f41
r11     0xcd0d0
r12     0x156703fcc
r13     0x29
r14     0x156700000
r15     0xa0008000
r16     0xd79600010724c080
r17     0x0
r18     0x0
r19     0x15987e200
r20     0x15672e700
r21     0x15987b5a0
r22     0x15987e628
r23     0x15987e628
r24     0x15672e790
r25     0x0
r26     0x0
r27     0x0
r28     0x0
r29     0x16b547190
lr      0x1080b2878
sp      0x16b5429a0
pc      0x1080b28a4
fault   0x0
```

### Platform

macOS

### LINKED ISSUE #1018: Resolve Vulkan location and structure
### Describe the feature

If we continue to use Vulkan, we should move https://github.com/goki/vulkan somewhere into the Cogent Core space, try again to merge it upstream, or use a better Vulkan package. We may also use WebGPU instead (see #507).

### Relevant code

_No response_

### LINKED ISSUE #1063: panic: vulkan error: vulkan error: feature not present (-8)
### Describe the bug

I got this error when trying to execute `go run cogentcore.org/core/examples/demo@main`, even though `core setup` showed me this message _core setup succeeded_

```
Platform: Linux
System platform: Linux
App version: dev
Core version: dev
Time: 2024-07-25 21:20:44

panic: vulkan error: vulkan error: feature not present (-8)

goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	/usr/lib/go-1.22/src/runtime/debug/stack.go:24 +0x5e
cogentcore.org/core/system.HandleRecoverBase({0xe58b20, 0xc00bc82080})
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/recover.go:50 +0x4b
cogentcore.org/core/core.handleRecover({0xe58b20, 0xc00bc82080})
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/recover.go:33 +0x4b
cogentcore.org/core/core.(*Stage).run.func1()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/stage.go:277 +0x24
panic({0xe58b20?, 0xc00bc82080?})
	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
cogentcore.org/core/vgpu.IfPanic(...)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/errors.go:39
cogentcore.org/core/vgpu.(*Device).MakeDevice(0xc00391c008, 0xc0000ef808)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/device.go:98 +0x2ff
cogentcore.org/core/vgpu.(*Surface).Init(0xc00391c000, 0xc0000ef808, 0xe13ee0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/surface.go:118 +0x15b
cogentcore.org/core/vgpu.NewSurface(0xc0000ef808, 0x23cfe40)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/surface.go:68 +0x45
cogentcore.org/core/system/driver/desktop.(*App).NewWindow.func2()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/driver/desktop/app.go:137 +0x87
cogentcore.org/core/system/driver/base.(*App).RunOnMain(0x0?, 0x0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/driver/base/app.go:90 +0xa9
cogentcore.org/core/system/driver/desktop.(*App).NewWindow(0x1d737c0, 0xc0037b2c60?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/driver/desktop/app.go:135 +0x474
cogentcore.org/core/core.newRenderWindow({0xc003d14100, 0x31}, {0xc0003260f0, 0x25}, 0xc0037b2c60)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/renderwindow.go:108 +0xa5
cogentcore.org/core/core.(*Stage).newRenderWindow(0xc003926b40)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:343 +0x20a
cogentcore.org/core/core.(*Stage).runWindow(0xc003926b40)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:226 +0x6dc
cogentcore.org/core/core.(*Stage).run(0x1?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/stage.go:280 +0x88
cogentcore.org/core/core.(*Stage).Run(0x0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/stage.go:259 +0x7a
cogentcore.org/core/core.(*Body).RunWindow(0x0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:69 +0x26
cogentcore.org/core/core.handleRecover({0xe58b20, 0xc007922080})
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/recover.go:69 +0x20a
cogentcore.org/core/core.(*Stage).run.func1()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/stage.go:277 +0x24
panic({0xe58b20?, 0xc007922080?})
	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
cogentcore.org/core/vgpu.IfPanic(...)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/errors.go:39
cogentcore.org/core/vgpu.(*Device).MakeDevice(0xc0036d0168, 0xc0000ef808)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/device.go:98 +0x2ff
cogentcore.org/core/vgpu.(*Surface).Init(0xc0036d0160, 0xc0000ef808, 0xe13ee0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/surface.go:118 +0x15b
cogentcore.org/core/vgpu.NewSurface(0xc0000ef808, 0x23ba800)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/vgpu/surface.go:68 +0x45
cogentcore.org/core/system/driver/desktop.(*App).NewWindow.func2()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/driver/desktop/app.go:137 +0x87
cogentcore.org/core/system/driver/base.(*App).RunOnMain(0x0?, 0x0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/driver/base/app.go:90 +0xa9
cogentcore.org/core/system/driver/desktop.(*App).NewWindow(0x1d737c0, 0xc0058e41e0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/system/driver/desktop/app.go:135 +0x474
cogentcore.org/core/core.newRenderWindow({0xc0030f1230, 0x22}, {0xfa60be, 0x10}, 0xc0058e41e0)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/renderwindow.go:108 +0xa5
cogentcore.org/core/core.(*Stage).newRenderWindow(0xc0054e1860)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:343 +0x20a
cogentcore.org/core/core.(*Stage).runWindow(0xc0054e1860)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:226 +0x6dc
cogentcore.org/core/core.(*Stage).run(0x41a0000042a00000?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/stage.go:280 +0x88
cogentcore.org/core/core.(*Stage).Run(0x0?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/stage.go:259 +0x7a
cogentcore.org/core/core.(*Body).RunWindow(0xc004cb6a88?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:69 +0x26
cogentcore.org/core/core.(*Body).RunMainWindow(0xc000350008?)
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/core/mainstage.go:59 +0x131
main.main()
	/home/user/go/pkg/mod/cogentcore.org/core@v0.3.1-0.20240725043440-7dbc33d1e076/examples/demo/demo.go:44 +0xcf

```

### How to reproduce

execute `go run cogentcore.org/core/examples/demo@main`

### Example code

_No response_

### Relevant output

_No response_

### Platform

Linux

### LINKED ISSUE #1101: Android Vulkan doesn't work
### Describe the bug

Compiled to apk using core pack android. Program installed fine but cannot run it.

### How to reproduce

download the demo, compiled to apk using core pack android. nearly 100 -150 mb apk file is made. Try to run in android

### Example code

_No response_

### Relevant output

_No response_

### Platform

Android

### LINKED ISSUE #1106: Vulkan: Loader not found
### Describe the bug

I'm trying to run the cogent hello world example on an arm64 mac. It compiles but doesn't run, I get the output below.

I've installed https://github.com/KhronosGroup/MoltenVK.

Any ideas what I'm missing?

### How to reproduce

Run the cogent hello world example on an arm64 mac.

### Example code

```go
package main

import (
	"cogentcore.org/core/core"
)

func main() {
	b := core.NewBody()
	core.NewButton(b).SetText("Hello, World!")
	b.RunMainWindow()
}
```

### Relevant output

```shell
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an invalid error was not accepted by the caller: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
panic: APIUnavailable: Vulkan: Loader not found

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x1?})
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/error.go:181 +0x214
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/error.go:188
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0x10546bc88?, 0x104dba4a0?)
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:274 +0x38
cogentcore.org/core/system/driver/desktop.(*App).InitVk(0x105f3f4c0)
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/desktop/app.go:85 +0xd0
cogentcore.org/core/system/driver/desktop.Init()
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/desktop/app.go:30 +0x28
cogentcore.org/core/system/driver.init.0()
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/driver_desktop.go:30 +0xcc
```

### Platform

macOS

### LINKED ISSUE #1115: MoltenVK missing for build (on macOS)
### Describe the bug

core build

### How to reproduce

core build

### Example code

```go
package main

import "cogentcore.org/core/core"

func main() {
        b := core.NewBody()
        core.NewButton(b).SetText("Hello, World!")
        b.RunMainWindow()
}
main.
```

### Relevant output

```shell
core build
go build -ldflags -s -w -X cogentcore.org/core/system.CoreVersion=v0.3.2-0.20240804044309-bbf00b5032c1 -o /Users/sergehulne/Documents/code/Go/core1/Core1
# app
/Users/sergehulne/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-amd64/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library 'MoltenVK' not found
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

core build failed: build: error building for platform darwin/amd64: failed to run "go build -ldflags -s -w -X cogentcore.org/core/system.CoreVersion=v0.3.2-0.20240804044309-bbf00b5032c1 -o /Users/sergehulne/Documents/code/Go/core1/Core1: exit status 1"
```

### Platform

macOS

### PR DESCRIPTION
**Pull request by rcoreilly**
This mega-branch contains a new version of `vgpu` that works with WebGPU instead of vulkan.

Overall WebGPU is much simpler and cleaner than vulkan, and, critically, works on the web.

The top-level `gpu` package contains the full implementation and supporting packages, replacing `vgpu` and associated packages.

`gpudraw` replaces `vdraw` and has an improved interface, updating the `system.Drawer` interface used for basic 2D image compositing during rendering.

This is not done yet but maybe @kkoreilly wants to make any comments on the gpudraw api at this point?

*(Edit from @kkoreilly):*
For GitHub purposes, this fixes #290, fixes #481, fixes #483, fixes #507, fixes #682, fixes #911, fixes #1018, fixes #1063, fixes #1101, fixes #1106, fixes #1115 (#507 and #682 are the primary issues)

### CODE REVIEW

**Comment by kkoreilly** [comment]
You can mark draft PRs as a draft, which I did for you.

**Reminders:**

1. We do still need to explore whether this actually works on VMs and old Linux devices, or whether we still need another fallback for Linux, which would require re-opening #682
2. ~~We still need to fold in the actual `go-webgpu` package~~
3. We still need to remove `vgpu` (and all of the `Vk` functions like `SetVkPerspective`)
4. We still need to update `xyz` and `system` etc to these changes

File: gpu/gpudraw/drawer.go [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+	"image/draw"
+	"sync"
+
+	"cogentcore.org/core/gpu"
+)
+
+// These draw.Op constants are provided so that users of this package don't
+// have to explicitly import "image/draw".  We also add the fill operation.
+const (
+	Over = draw.Over
```
Comment (kkoreilly) [inline gpu/gpudraw/drawer.go:21]: What about adding some docs for these? What is `Fill`?

File: gpu/gpudraw/drawer.go [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+	Src  = draw.Src
+	Fill = draw.Src + 1
+)
+
+// AllocChunk is number of images / matrix elements to allocate
+// at a time, to reduce number of reallocations.
+// Should be set to the rough scale of number of items expected.
+var AllocChunk = 16
```
Comment (kkoreilly) [inline gpu/gpudraw/drawer.go:36]: Is `Chunk` better than something like `Batch`?

File: gpu/gpudraw/drawused.go [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+
+// CopyUsed copies the current Use* texture to render target.
+// Must have called StartDraw and a Use* method first!
+//   - dp is the destination point.
+//   - src is the source image. If an image.Uniform, fast Fill is done.
+//   - sr is the source region, if zero full src is used.
+//   - op is the drawing operation: Src = copy source directly (blit),
+//     Over = alpha blend with existing.
+//   - flipY = flipY axis when drawing this image.
+func (dw *Drawer) CopyUsed(dp image.Point, sr image.Rectangle, op draw.Op, flipY bool) {
```
Comment (kkoreilly) [inline gpu/gpudraw/drawused.go:64]: These functions used to not have `Used` suffixes, right? Can you explain the reasoning for that change? If you want to make this change, you also have to update `system.Drawer` accordingly.

**Review by kkoreilly — COMMENTED** [review]
Overall `gpudraw` API seems reasonable except for my specific comments.

File: gpu/gpudraw/drawused.go (hunk 3 above)
Comment (rcoreilly) [reply gpu/gpudraw/drawused.go:64]: see the README   also I forgot to check in draw.go

File: gpu/gpudraw/drawer.go (hunk 2 above)
Comment (rcoreilly) [reply gpu/gpudraw/drawer.go:36]: no.

File: system/drawer.go [hunk 4]
```diff
@@ -6,258 +6,126 @@ package system
...
+// same semantics as golang.org/x/image/draw.Copy, with the destination
+// implicit in the Drawer target.
+//   - Must have called Start first!
+//   - dp is the destination point.
+//   - src is the source image. If an image.Uniform, fast Fill is done.
+//   - sr is the source region, if zero full src is used; must have for Uniform.
+//   - op is the drawing operation: Src = copy source directly (blit),
+//     Over = alpha blend with existing.
+func (dw *DrawerBase) Copy(dp image.Point, src image.Image, sr image.Rectangle, op draw.Op) {
+	draw.Draw(dw.Image, image.Rectangle{dp, dp.Add(src.Bounds().Size())}, src, sr.Min, op)
```
Comment (kkoreilly) [inline system/drawer.go:109]: This seems wrong to me, but I guess this is what we had before and it worked.

File: system/driver/android/app.go [hunk 5]
```diff
@@ -108,12 +108,7 @@ func (a *App) SetSystemWindow(winptr uintptr) error {
 	sf.SetRender(&sys.Render)
 	// sys.Mem.Vars.NDescs = vgpu.MaxTexturesPerSet
 	sys.Config()
-	a.Draw = &vdraw.Drawer{
-		Sys:     *sys,
-		YIsDown: true,
-	}
-	// a.Draw.ConfigSys()
-	a.Draw.ConfigSurface(sf, vgpu.MaxTexturesPerSet)
+	a.Draw = gpudraw.NewDrawerSurface(sf)
```
Comment (kkoreilly) [inline system/driver/android/app.go]: We don't need to set any `System` or call any other config thing here?

File: system/driver/desktop/app.go [hunk 6]
```diff
@@ -73,13 +72,11 @@ func (a *App) MainLoop() {
...
 
-// InitVk initializes glfw, vulkan, vgpu, and the screens.
-func (a *App) InitVk() {
+// InitGPU initializes glfw, gpu, and the screens.
+func (a *App) InitGPU() {
 	if err := glfw.Init(); err != nil {
 		log.Fatalln("system/driver/desktop failed to initialize glfw:", err)
 	}
-	vk.SetGetInstanceProcAddr(glfw.GetVulkanGetInstanceProcAddress())
-	vk.Init()
```
Comment (kkoreilly) [inline system/driver/desktop/app.go:82]: I'm pretty sure you still need to call `glfw.Init` or `gpu.Init` somewhere.

File: system/driver/desktop/window.go [hunk 7]
```diff
@@ -301,12 +300,13 @@ func (w *Window) Close() {
...
-		vk.DeviceWaitIdle(w.Draw.Surf.Device.Device)
+		// vk.DeviceWaitIdle(w.Draw.Surf.Device.Device)
+		w.Draw.Sys.WaitDone()
 		if w.DestroyGPUFunc != nil {
 			w.DestroyGPUFunc()
 		}
-		w.Draw.Destroy()
-		w.Draw.Surf.Destroy()
+		w.Draw.Release()
+		w.Draw.Surface().(*wgpu.Surface).Release()
```
Comment (kkoreilly) [inline system/driver/desktop/window.go]: Do you really need a type assertion here?

File: system/examples/drawtri/drawtri.go [hunk 8]
```diff
@@ -35,30 +37,30 @@ func main() {
...
 
+		sh := pl.AddShader("trianglelit")
+		sh.OpenCode(trianglelit)
+		pl.AddEntry(sh, gpu.VertexShader, "vs_main")
+		pl.AddEntry(sh, gpu.FragmentShader, "fs_main")
+
+		sy.Config()
 		destroy := func() {
-			sy.Destroy()
+			sy.Release()
```
Comment (kkoreilly) [inline system/examples/drawtri/drawtri.go]: What is the story with `Destroy` vs `Release` terminology?

**Review by kkoreilly — COMMENTED** [review]
There don't appear to be any obvious issues that would make it fail like that; is it possible that `gpu` and `system` are both doing the same thing twice? The error message seems to indicate something like that.

File: system/driver/desktop/app.go (hunk 6 above)
Comment (kkoreilly) [reply system/driver/desktop/app.go:82]: Oh wait never mind; you're calling it right there, and there is no `wgpu.Init`.

**Comment by theclapp** [comment]
Two things:

1. Wikipedia says WebGPU is built on top of Vulkan (or Metal or Direct3D). Is that correct? How will changing to WebGPU bypass Vulkan? As I understand it, Metal is macOS-specific and Direct3D is Windows-specific; how will this help Linux users? (Not saying it won't, just asking, for my own education. If this is documented in another issue, feel free to point me to it.)
2. If you'll tell me how, I'm happy to test this branch on my Linux and/or Windows VMs. (VirtualBox 7.0.20, Debian v12 & Windows 10).

**Comment by kkoreilly** [comment]
Yes, it is built on Vulkan, Metal, and Direct3D. This will help macOS and Windows users since there will be no Vulkan needed. This will help Linux users because WebGPU requires fewer Vulkan features than we used to be using; if you look at the Vulkan issues people have filed here, most of them are a `feature not present` panic. Moreover, it is maybe possible that there is an OpenGL backup for WebGPU on Linux. However, if there is not, and it still does not work, we will implement a direct render 2D backup on Linux that just uses platform-specific APIs.

It would be greatly appreciated if you could test this on your VMs; you can just clone this repo, `git switch wgpu`, and run `examples/demo` and `examples/xyz` both locally with `core run` and on the web with `core run web` and Chrome. Thank you!

**Comment by theclapp** [comment]
On a Debian 12, VirtualBox 7.0.20, r163906, VM, running the "basic" ("hello world" button) demo, got a panic
<details>
Mouse-over the "three dots" drop down, move away, and move back, panic:

```sh
1618 lmc osboxes 08/12 11:18:45 AM ~/host/Users/lmc/goget/src/github.com/cogentcore/core/examples/basic
RUST_BACKTRACE=1 core run -v
Mon Aug 12 11:18:46 AM EDT 2024
go build -ldflags -s -w -X 'cogentcore.org/core/core.AppIcon=<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 1 1"><path d="M.833.675a.35.35 0 1 1 0-.35" style="stroke:#005bc0;stroke-width:.27;fill:none"/><circle cx=".53" cy=".5" r=".23" style="fill:#fbbd0e;stroke:none"/></svg>' -X cogentcore.org/core/system.AppVersion=v0.3.1-180-g9fc40dd81 -X cogentcore.org/core/system.CoreVersion=v0.3.1-180-g9fc40dd81 -o /home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/examples/basic/Cogent Core Basic
/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/examples/basic/Cogent Core Basic 
[wgpu] [Warn] Unable to find extension: VK_EXT_swapchain_colorspace
2024/08/12 11:18:59 ERROR wgpu.(*CommandEncoder).Finish(): Validation Error

Caused by:
    In wgpuCommandEncoderFinish
    Command encoder is invalid
 | cogentcore.org/core/gpu.(*GraphicsSystem).SubmitRender /home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gsystem.go:265
[wgpu] [Error] No work has been submitted for this frame
2024/08/12 11:18:59 ERROR wgpu.(*CommandEncoder).Finish(): Validation Error

Caused by:
    In wgpuCommandEncoderFinish
    Command encoder is invalid
 | cogentcore.org/core/gpu.(*GraphicsSystem).SubmitRender /home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gsystem.go:265
[wgpu] [Error] No work has been submitted for this frame
2024/08/12 11:19:02 ERROR wgpu.(*CommandEncoder).Finish(): Validation Error

Caused by:
    In wgpuCommandEncoderFinish
    Command encoder is invalid
 | cogentcore.org/core/gpu.(*GraphicsSystem).SubmitRender /home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gsystem.go:265
[wgpu] [Error] No work has been submitted for this frame
thread '<unnamed>' panicked at src/lib.rs:3886:40:
invalid texture
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7fed2e67ee2c m=5 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 23 gp=0xc000102700 m=5 mp=0xc000100008 [syscall]:
runtime.cgocall(0xb3c2c0, 0xc00003b938)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00003b910 sp=0xc00003b8d8 pc=0x44730b
github.com/cogentcore/webgpu/wgpu._Cfunc_gowebgpu_texture_create_view(0x0, 0x0, 0x36052a0, 0xc0002b0780)
	_cgo_gotypes.go:1775 +0x4c fp=0xc00003b938 sp=0xc00003b910 pc=0x72562c
github.com/cogentcore/webgpu/wgpu.(*Texture).CreateView.func3(0x111fb80?, 0x0, 0xc0002b0780)
	/home/lmc/goget/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/texture.go:72 +0xc6 fp=0xc00003b990 sp=0xc00003b938 pc=0x7445c6
github.com/cogentcore/webgpu/wgpu.(*Texture).CreateView(0xc0002b0770, 0x0?)
	/home/lmc/goget/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/texture.go:72 +0x1f6 fp=0xc00003ba38 sp=0xc00003b990 pc=0x744356
cogentcore.org/core/gpu.(*Surface).GetCurrentTexture(0xc000280008)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/surface.go:129 +0x95 fp=0xc00003ba78 sp=0xc00003ba38 pc=0x7622f5
cogentcore.org/core/gpu.(*GraphicsSystem).beginRenderPass(0xc0002681e0)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gsystem.go:215 +0x32 fp=0xc00003bac0 sp=0xc00003ba78 pc=0x75ee52
cogentcore.org/core/gpu.(*GraphicsSystem).BeginRenderPass(0xc0002681e0)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gsystem.go:234 +0x18 fp=0xc00003baf0 sp=0xc00003bac0 pc=0x75ef38
cogentcore.org/core/gpu/gpudraw.(*Drawer).drawAll(0xc00011c000)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gpudraw/system.go:124 +0xbe fp=0xc00003bb98 sp=0xc00003baf0 pc=0x77073e
cogentcore.org/core/gpu/gpudraw.(*Drawer).End(0xc00011c000)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/gpu/gpudraw/drawer.go:127 +0x8d fp=0xc00003bbd8 sp=0xc00003bb98 pc=0x76e68d
cogentcore.org/core/core.(*renderWindow).renderWindow(0xc0002680a0)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:695 +0x9e7 fp=0xc00003be18 sp=0xc00003bbd8 pc=0x96ec87
cogentcore.org/core/core.(*renderWindow).handleWindowEvents(0xc0002680a0, {0x14cb098, 0xc000b3b340})
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:428 +0x479 fp=0xc00003bee0 sp=0xc00003be18 pc=0x96df19
cogentcore.org/core/core.(*renderWindow).handleEvent(0xc0002680a0, {0x14cb098, 0xc000b3b340})
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:412 +0x11c fp=0xc00003bf50 sp=0xc00003bee0 pc=0x96d9fc
cogentcore.org/core/core.(*renderWindow).eventLoop(0xc0002680a0)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:380 +0x87 fp=0xc00003bfc8 sp=0xc00003bf50 pc=0x96d7c7
cogentcore.org/core/core.(*renderWindow).goStartEventLoop.gowrap1()
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:351 +0x25 fp=0xc00003bfe0 sp=0xc00003bfc8 pc=0x96d705
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00003bfe8 sp=0xc00003bfe0 pc=0x4b1cc1
created by cogentcore.org/core/core.(*renderWindow).goStartEventLoop in goroutine 1
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:351 +0x65

goroutine 1 gp=0xc0000061c0 m=0 mp=0x1d65a60 [syscall, locked to thread]:
runtime.cgocall(0xb3a840, 0xc0000cbe30)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0000cbe08 sp=0xc0000cbdd0 pc=0x44730b
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEvents()
	_cgo_gotypes.go:2566 +0x3f fp=0xc0000cbe30 sp=0xc0000cbe08 pc=0x74df7f
github.com/go-gl/glfw/v3.3/glfw.WaitEvents()
	/home/lmc/goget/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/window.go:949 +0x13 fp=0xc0000cbe58 sp=0xc0000cbe30 pc=0x7569b3
cogentcore.org/core/system/driver/desktop.(*App).MainLoop(0x1d652c0)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/system/driver/desktop/app.go:70 +0x125 fp=0xc0000cbed8 sp=0xc0000cbe58 pc=0x87fb65
cogentcore.org/core/core.Wait()
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:39 +0x52 fp=0xc0000cbf00 sp=0xc0000cbed8 pc=0x96bd92
cogentcore.org/core/core.(*Body).RunMainWindow(0x14ba920?)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/mainstage.go:46 +0x2d fp=0xc0000cbf18 sp=0xc0000cbf00 pc=0x96416d
main.main()
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/examples/basic/basic.go:8 +0xac fp=0xc0000cbf50 sp=0xc0000cbf18 pc=0xb2394c
runtime.main()
	/usr/local/go/src/runtime/proc.go:271 +0x29d fp=0xc0000cbfe0 sp=0xc0000cbf50 pc=0x47e83d
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000cbfe8 sp=0xc0000cbfe0 pc=0x4b1cc1

goroutine 2 gp=0xc000006c40 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000054fa8 sp=0xc000054f88 pc=0x47ec6e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:326 +0xb3 fp=0xc000054fe0 sp=0xc000054fa8 pc=0x47eaf3
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x4b1cc1
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000007180 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000055780 sp=0xc000055760 pc=0x47ec6e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.bgsweep(0xc00007e000)
	/usr/local/go/src/runtime/mgcsweep.go:318 +0xdf fp=0xc0000557c8 sp=0xc000055780 pc=0x4691ff
runtime.gcenable.gowrap1()
	/usr/local/go/src/runtime/mgc.go:203 +0x25 fp=0xc0000557e0 sp=0xc0000557c8 pc=0x45db05
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000557e8 sp=0xc0000557e0 pc=0x4b1cc1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000007340 m=nil [GC scavenge wait]:
runtime.gopark(0x1d65080?, 0x14b3740?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000055f78 sp=0xc000055f58 pc=0x47ec6e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x1d65080)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000055fa8 sp=0xc000055f78 pc=0x466ba9
runtime.bgscavenge(0xc00007e000)
	/usr/local/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000055fc8 sp=0xc000055fa8 pc=0x467159
runtime.gcenable.gowrap2()
	/usr/local/go/src/runtime/mgc.go:204 +0x25 fp=0xc000055fe0 sp=0xc000055fc8 pc=0x45daa5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x4b1cc1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc000007c00 m=nil [finalizer wait]:
runtime.gopark(0xc000054648?, 0x4511e5?, 0xa8?, 0x1?, 0xc0000061c0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000054620 sp=0xc000054600 pc=0x47ec6e
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:194 +0x107 fp=0xc0000547e0 sp=0xc000054620 pc=0x45cb47
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000547e8 sp=0xc0000547e0 pc=0x4b1cc1
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:164 +0x3d

goroutine 6 gp=0xc00026ae00 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000056750 sp=0xc000056730 pc=0x47ec6e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc0000567e0 sp=0xc000056750 pc=0x45fbe5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x4b1cc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 18 gp=0xc0004a8000 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000050750 sp=0xc000050730 pc=0x47ec6e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc0000507e0 sp=0xc000050750 pc=0x45fbe5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000507e8 sp=0xc0000507e0 pc=0x4b1cc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 19 gp=0xc0004a81c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000050f50 sp=0xc000050f30 pc=0x47ec6e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc000050fe0 sp=0xc000050f50 pc=0x45fbe5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000050fe8 sp=0xc000050fe0 pc=0x4b1cc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 20 gp=0xc0004a8380 m=nil [GC worker (idle)]:
runtime.gopark(0x69bb646fe13?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000051750 sp=0xc000051730 pc=0x47ec6e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc0000517e0 sp=0xc000051750 pc=0x45fbe5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000517e8 sp=0xc0000517e0 pc=0x4b1cc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 34 gp=0xc000102380 m=nil [GC worker (idle)]:
runtime.gopark(0x69bb6463153?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000114750 sp=0xc000114730 pc=0x47ec6e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc0001147e0 sp=0xc000114750 pc=0x45fbe5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0001147e8 sp=0xc0001147e0 pc=0x4b1cc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 21 gp=0xc0004a8540 m=nil [GC worker (idle)]:
runtime.gopark(0x69bb63e75af?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000051f50 sp=0xc000051f30 pc=0x47ec6e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc000051fe0 sp=0xc000051f50 pc=0x45fbe5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x4b1cc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 22 gp=0xc000102540 m=nil [select]:
runtime.gopark(0xc0004fff58?, 0x2?, 0x98?, 0xfe?, 0xc0004fff44?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc0004ffde8 sp=0xc0004ffdc8 pc=0x47ec6e
runtime.selectgo(0xc0004fff58, 0xc0004fff40, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc0004fff08 sp=0xc0004ffde8 pc=0x490925
cogentcore.org/core/system/driver/base.(*Window[...]).WinLoop(0x14c8b40)
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/system/driver/base/window.go:93 +0x125 fp=0xc0004fffc0 sp=0xc0004fff08 pc=0x887525
cogentcore.org/core/system/driver/desktop.(*App).NewWindow.gowrap1()
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/system/driver/desktop/app.go:168 +0x25 fp=0xc0004fffe0 sp=0xc0004fffc0 pc=0x880865
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0004fffe8 sp=0xc0004fffe0 pc=0x4b1cc1
created by cogentcore.org/core/system/driver/desktop.(*App).NewWindow in goroutine 1
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/system/driver/desktop/app.go:168 +0xa46

goroutine 7 gp=0xc0004a8700 m=nil [semacquire]:
runtime.gopark(0x0?, 0x0?, 0xa0?, 0x2e?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc0001136f0 sp=0xc0001136d0 pc=0x47ec6e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.semacquire1(0x1de7e18, 0x0, 0x1, 0x0, 0x12)
	/usr/local/go/src/runtime/sema.go:160 +0x225 fp=0xc000113758 sp=0xc0001136f0 pc=0x491965
sync.runtime_Semacquire(0x0?)
	/usr/local/go/src/runtime/sema.go:62 +0x25 fp=0xc000113790 sp=0xc000113758 pc=0x4adee5
sync.(*WaitGroup).Wait(0x0?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x48 fp=0xc0001137b8 sp=0xc000113790 pc=0x4cfb68
cogentcore.org/core/core.Wait.func2()
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:36 +0x37 fp=0xc0001137e0 sp=0xc0001137b8 pc=0x9d7777
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0001137e8 sp=0xc0001137e0 pc=0x4b1cc1
created by cogentcore.org/core/core.Wait in goroutine 1
	/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/core/renderwindow.go:34 +0x3e

rax    0x0
rbx    0x5131
rcx    0x7fed2e67ee2c
rdx    0x6
rdi    0x512d
rsi    0x5131
rbp    0x7fece70be6c0
rsp    0x7fece70bd800
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x0
r14    0x1de7938
r15    0x7fece70be6c0
rip    0x7fed2e67ee2c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
core run failed: failed to run "/home/lmc/host/Users/lmc/goget/src/github.com/cogentcore/core/examples/basic/Cogent Core Basic : exit status 2"
```
</details>

**Comment by theclapp** [comment]
On a Windows 10 VM, `core build -v` failed.

In case it matters: I may not be using the C compiler you expect or are used to, which might make a difference. I got it from Cygwin.

```sh
#cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/bin/../lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.4.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,d,fortran,lto,objc,obj-c++,jit --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --disable-multilib --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (GCC)
```

<details>

<summary> Details of build failure </summary>

Basically lots of undefined references. I cleaned it up to be only unique symbols.

```sh
go build -ldflags -s -w -X 'cogentcore.org/core/core.AppIcon=<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 1 1"><path d="M.833.675a.35.35 0 1 1 0-.35" style="stroke:#005bc0;stroke-width:.27;fill:none"/><circle cx=".53" cy=".5" r=".23" style="fill:#fbbd0e;stroke:none"/></svg>' -X cogentcore.org/core/system.AppVersion=v0.3.1-180-g9fc40dd81 -X cogentcore.org/core/system.CoreVersion=v0.3.1-180-g9fc40dd81 -o E:\goget\src\github.com\cogentcore\core\examples\basic\Cogent Core Basic.exe
# cogentcore.org/core/examples/basic
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running x86_64-w64-mingw32-gcc.exe failed: exit status 1
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: C:/Users/lmc/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/lib/windows/amd64/libwgpu_native.a(wgpu_hal-f9bed302dd7081d2.wgpu_hal.96b79142f997d28f-cgu.01.rcgu.o):wgpu_hal.96b79142f:(.text+0x158a): undefined reference to `wglGetCurrentContext'
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: C:/Users/lmc/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/lib/windows/amd64/libwgpu_native.a(wgpu_hal-f9bed302dd7081d2.wgpu_hal.96b79142f997d28f-cgu.01.rcgu.o):wgpu_hal.96b79142f:(.text+0x1598): undefined reference to `wglMakeCurrent'
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: C:/Users/lmc/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/lib/windows/amd64/libwgpu_native.a(wgpu_hal-f9bed302dd7081d2.wgpu_hal.96b79142f997d28f-cgu.15.rcgu.o):wgpu_hal.96b79142f:(.text+0x525c): undefined reference to `wglDeleteContext'
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: C:/Users/lmc/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/lib/windows/amd64/libwgpu_native.a(wgpu_hal-f9bed302dd7081d2.wgpu_hal.96b79142f997d28f-cgu.15.rcgu.o):wgpu_hal.96b79142f:(.text+0x536e): undefined reference to `wglGetProcAddress'
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: C:/Users/lmc/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/lib/windows/amd64/libwgpu_native.a(wgpu_hal-f9bed302dd7081d2.wgpu_hal.96b79142f997d28f-cgu.15.rcgu.o):wgpu_hal.96b79142f:(.text+0x56b5): undefined reference to `GetPixelFormat'
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: C:/Users/lmc/go/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20240810234500-5911b906308b/wgpu/lib/windows/amd64/libwgpu_native.a(wgpu_hal-f9bed302dd7081d2.wgpu_hal.96b79142f997d28f-cgu.15.rcgu.o):wgpu_hal.96b79142f:(.text+0x6be0): undefined reference to `wglCreateContext'
collect2: error: ld returned 1 exit status
```
</details>

**Comment by rcoreilly** [comment]
@theclapp did the linux vm run work at the start, and only crashed on that mouse-over?  if so that is very strange because that code path would be used throughout, so it is unclear why it would fail there.

also we fixed the link issue on windows last night -- I just updated the core go mod to use the latest -- give it another try!

**Comment by theclapp** [comment]
> did the linux vm run work at the start, and only crashed on that mouse-over?

Yes. The larger "demo" exhibits similar behavior: It works fine (... sort of) _so long as_ I'm _very quick_ and don't hover long enough over anything to cause a tooltip. The tooltips seem to kill it.

> also we fixed the link issue on windows last night -- I just updated the core go mod to use the latest -- give it another try!

Yes, the windows demo now works (tooltips and everything! :).

**Comment by kkoreilly** [comment]
> The tooltips seem to kill it.

@theclapp We can reproduce this issue on our Linux device and will work on fixing it now.

**Comment by theclapp** [comment]
Can confirm that the Linux version works on my VM. 🎉 

One bit of weirdness so far, which might just be an existing bug, since I see the same thing under the native macOS demo: 
* Click Widgets
* Click Buttons
* *Hover* but don't click any of the top row of drop-downs -- press Ctrl-shift-1 or Ctrl-3 -- the hotkey works
* *Click* the dropdown but do not move the mouse, so the drop-down pops up but the mouse is still over the button -- **Neither of the Ctrl-Shift-1 nor Ctrl-3 hotkeys work**
* Move the mouse to hover the drop-down, and then the hotkeys work

Also, since clicking the drop-down dismisses it, it seems like using the hotkeys should dismiss it too, but they don't.

Anyway: Yay! Nice work! :)

**Comment by kkoreilly** [comment]
Great that it works on your Linux VM! It is working on all of our macOS, Windows, Linux, Android, and Web devices (but not yet iOS). I confirmed that button menu bug has been around since at least May 6th (2024), so it is unrelated. It would be great if you could file a separate issue for that. Thank you!

File: cmd/core/cmd/registry_others.go [hunk 9]
```diff
@@ -0,0 +1,7 @@
+//go:build !windows
```
Comment (kkoreilly) [inline cmd/core/cmd/registry_others.go]: `registry_notwindows.go` or `registry_noop.go` would be more standard names

File: cmd/core/cmd/registry_windows.go [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+	"fmt"
+	"strings"
+
+	"cogentcore.org/core/base/errors"
+	"golang.org/x/sys/windows/registry"
+)
+
+// WindowsRegistryAddPath adds given path to the system path in the
+// windows registry.  Path string must be properly escaped when passed
+// as a double-quote string, e.g., "C:\\w64devkit\\bin".
```
Comment (kkoreilly) [inline cmd/core/cmd/registry_windows.go]: This is obvious and true for all Go strings.

File: cmd/core/cmd/registry_windows.go [hunk 11]
```diff
@@ -0,0 +1,43 @@
...
+// If adding multiple paths, put ; between them, but do NOT add a leading
+// or trailing semicolon -- these will be handled automatically.
+func WindowsRegistryAddPath(path string) error {
```
Comment (kkoreilly) [inline cmd/core/cmd/registry_windows.go]: Unexport.

File: cmd/core/cmd/registry_windows.go [hunk 12]
```diff
@@ -0,0 +1,43 @@
...
+	k, err := registry.OpenKey(registry.LOCAL_MACHINE, `System\CurrentControlSet\Control\Session Manager\Environment`, registry.QUERY_VALUE|registry.SET_VALUE)
+	if errors.Log(err) != nil {
```
Comment (kkoreilly) [inline cmd/core/cmd/registry_windows.go]: Do not log errors here.

File: cmd/core/cmd/registry_windows.go [hunk 13]
```diff
@@ -0,0 +1,43 @@
...
+	if strings.Contains(s, scpath) {
+		fmt.Printf("Path %s already in existing Path: %s\n", path, s)
+		return nil
+	}
+	s += path + ";"
+	err = k.SetStringValue("Path", s)
+	if errors.Log(err) != nil {
+		return err
+	}
+	fmt.Printf("Path: %s added to system Path: re-start any open shells to use\n", path)
```
Comment (kkoreilly) [inline cmd/core/cmd/registry_windows.go]: Use `logx.PrintfDebug`. Use `%q` without a colon. All-caps PATH for `system PATH`. Do not specify need to restart shell; that is stated in docs.

File: cmd/core/cmd/setup.go [hunk 14]
```diff
@@ -58,7 +58,7 @@ func Setup(c *config.Config) error { //types:add
 			if err != nil {
 				return err
 			}
-			logx.PrintlnWarn("### IMPORTANT: ###\nYou need to add C:\\w64devkit\\bin to your PATH\nClick the Windows menu and type 'environment', and it will show you a control panel item to set environment variables. At the bottom of the dialog, click on Environment Variables, then on the 'Path' variable in either the User or System section (System is applied to all users). You will need to restart your shell/prompt/terminal to apply the changes.")
+			WindowsRegistryAddPath("C:\\w64devkit\\bin")
```
Comment (kkoreilly) [inline cmd/core/cmd/setup.go]: Handle error here with `if err != nil { return err }`.

**Review by kkoreilly — CHANGES_REQUESTED** [review]

File: cmd/core/cmd/setup.go (hunk 14 above)
Comment (kkoreilly) [reply cmd/core/cmd/setup.go]: Also, you should probably just use backticks to avoid the double escaping need.

File: cmd/core/cmd/registry_windows.go (hunk 13 above)
Comment (rcoreilly) [reply cmd/core/cmd/registry_windows.go]: the registry lists it as "Path" not "PATH".

File: cmd/core/cmd/registry_windows.go (hunk 10 above)
Comment (rcoreilly) [reply cmd/core/cmd/registry_windows.go]: I had to look it up (of course).  what is obvious to you may not be to others..

Comment (kkoreilly) [reply cmd/core/cmd/registry_windows.go]: Just use backticks and don't document it. It would be ridiculous to have every function document how to specify the builtin types. `This function takes a 32-bit signed integer value. You can pass this as a variable or untyped integer constant, which can be expressed using decimal (ex: 4), hexadecimal (ex: 0xf), or octal (ex: 0o777) notation`. If you don't remember something about the language, it is incumbent upon you to figure that out, not the documentation. Again, use backticks and don't document it.

**Comment by kkoreilly** [comment]
I verified that this works on all browsers on all platforms to the extent possible:

Full support on:
- Chrome and Opera on macOS and Windows
- Edge on Windows

2D backup support on:
- Firefox on macOS, Windows, Linux, and Android
- Safari on macOS and iOS
- Chrome on Linux and Android

Note that we will gradually enable support for the current 2D backup platforms as they develop sufficient support, but currently they do not have such (#1144).

Additionally, I have verified that this works natively on macOS, Windows, Linux, iOS, and Android. Therefore, this is ready to be merged.

**Review by kkoreilly — APPROVED** [review]

**Comment by theclapp** [comment]
Nice work!

Can confirm it still works on my Debian Linux VM, and my Windows 10 VM.

The macOS native version doesn't seem to spike my laptop fans any more, either, so that's great, too. (Detail: it doesn't spike my "cpu package gpu" power usage, which was, I think, the "smoking gun" on the fans.)

**Comment by rcoreilly** [comment]
@theclapp great news on the power usage on intel mac -- I had noticed on my intel mac that the vulkan version seemed to push the fans a lot.

Could you also run this command:

```
go run cogentcore.org/core/gpu/cmd/webgpuinfo@latest 
```

on your linux vm and report the results here?  I'm curious what the "backend type" says there, and what the limits are, etc.  And you've tried examples/xyz on it and that all works?

**Comment by theclapp** [comment]
<details>
<summary>webgpuinfo output</summary>

```
go: downloading cogentcore.org/core v0.3.2
[wgpu] [Warn] Unable to find extension: VK_EXT_swapchain_colorspace

########################
WebGPU Adapter number: 0
{
        "VendorId": 65541,
        "VendorName": "0x10005",
        "Architecture": "",
        "DeviceId": 0,
        "Name": "0x0",
        "DriverDescription": "llvmpipe (LLVM 15.0.6, 256 bits)",
        "AdapterType": 2,
        "BackendType": 6
}

{
        "Limits": {
                "MaxTextureDimension1D": 16384,
                "MaxTextureDimension2D": 16384,
                "MaxTextureDimension3D": 4096,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 1000,
                "MaxDynamicUniformBuffersPerPipelineLayout": 256,
                "MaxDynamicStorageBuffersPerPipelineLayout": 256,
                "MaxSampledTexturesPerShaderStage": 128,
                "MaxSamplersPerShaderStage": 32,
                "MaxStorageBuffersPerShaderStage": 32,
                "MaxStorageTexturesPerShaderStage": 64,
                "MaxUniformBuffersPerShaderStage": 15,
                "MaxUniformBufferBindingSize": 65536,
                "MaxStorageBufferBindingSize": 134217728,
                "MinUniformBufferOffsetAlignment": 32,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 2147483647,
                "MaxVertexAttributes": 32,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 128,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 32768,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 1024,
                "MaxComputeWorkgroupsPerDimension": 65535,
                "MaxPushConstantSize": 775102547
        }
}


########################
WebGPU Adapter number: 1
{
        "VendorId": 65541,
        "VendorName": "0x10005",
        "Architecture": "",
        "DeviceId": 0,
        "Name": "0x0",
        "DriverDescription": "llvmpipe (LLVM 15.0.6, 256 bits)",
        "AdapterType": 2,
        "BackendType": 7
}

{
        "Limits": {
                "MaxTextureDimension1D": 16384,
                "MaxTextureDimension2D": 16384,
                "MaxTextureDimension3D": 2048,
                "MaxTextureArrayLayers": 2048,
                "MaxBindGroups": 8,
                "MaxBindingsPerBindGroup": 65535,
                "MaxDynamicUniformBuffersPerPipelineLayout": 15,
                "MaxDynamicStorageBuffersPerPipelineLayout": 16,
                "MaxSampledTexturesPerShaderStage": 16,
                "MaxSamplersPerShaderStage": 16,
                "MaxStorageBuffersPerShaderStage": 16,
                "MaxStorageTexturesPerShaderStage": 32,
                "MaxUniformBuffersPerShaderStage": 15,
                "MaxUniformBufferBindingSize": 65536,
                "MaxStorageBufferBindingSize": 134217728,
                "MinUniformBufferOffsetAlignment": 32,
                "MinStorageBufferOffsetAlignment": 32,
                "MaxVertexBuffers": 16,
                "MaxBufferSize": 2147483647,
                "MaxVertexAttributes": 16,
                "MaxVertexBufferArrayStride": 2048,
                "MaxInterStageShaderComponents": 128,
                "MaxInterStageShaderVariables": 0,
                "MaxColorAttachments": 0,
                "MaxColorAttachmentBytesPerSample": 0,
                "MaxComputeWorkgroupStorageSize": 32768,
                "MaxComputeInvocationsPerWorkgroup": 1024,
                "MaxComputeWorkgroupSizeX": 1024,
                "MaxComputeWorkgroupSizeY": 1024,
                "MaxComputeWorkgroupSizeZ": 1024,
                "MaxComputeWorkgroupsPerDimension": 65535,
                "MaxPushConstantSize": 0
        }
}
```
</details>

And yes, the xyz demo seems to work, too. 🎉

**Comment by kkoreilly** [comment]
Great, thank you for the information!

**Comment by kkoreilly** [comment]
Thank you!

**Comment by kkoreilly** [comment]
Yes, 2D works automatically on all platforms on which WebGPU is not yet supported.
